destination: ./_site
auto:        false
lsi:         false
server_port: 4000
markdown:    kramdown
#permalink:   date
permalink:   pretty
paginate:    5
kramdown:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
plugins:     [ jekyll-paginate ]
exclude:
  - README.txt
  - Rakefile
